In [5]:
# Import required libraries

import pandas as pd
import numpy as np

from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [6]:
wine = load_wine()
df = pd.DataFrame(wine.data, columns=wine.feature_names)
df['target'] = wine.target
df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0


In [7]:
print("Dataset Shape:", df.shape)

print("\nColumns:", df.columns)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nTarget Value Counts:")
print(df['target'].value_counts())

Dataset Shape: (178, 14)

Columns: Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline', 'target'],
      dtype='object')

Missing Values:
alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
target                          0
dtype: int64

Target Value Counts:
target
1    71
0    59
2    48
Name: count, dtype: int64


In [8]:
X = df.drop('target', axis=1)
y = df['target']

print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

Feature Shape: (178, 13)
Target Shape: (178,)


In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print("Training Data Shape:", X_train.shape)
print("Testing Data Shape:", X_test.shape)

Training Data Shape: (142, 13)
Testing Data Shape: (36, 13)


## GAUSSIAN NAIVE BAYES

In [11]:
gaussian_model = GaussianNB()

gaussian_model.fit(X_train, y_train)
gaussian_predictions = gaussian_model.predict(X_test)

gaussian_accuracy = accuracy_score(y_test, gaussian_predictions)
print("Gaussian Naive Bayes Accuracy:", gaussian_accuracy)

Gaussian Naive Bayes Accuracy: 1.0


In [14]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, gaussian_predictions))

print("\nClassification Report:\n")
print(classification_report(y_test, gaussian_predictions))

Confusion Matrix:
[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]

Classification Report:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36



## MULTINOMIAL NAIVE BAYES

In [16]:
multinomial_model = MultinomialNB()

multinomial_model.fit(X_train, y_train)
multinomial_predictions = multinomial_model.predict(X_test)

multinomial_accuracy = accuracy_score(y_test, multinomial_predictions)
print("Multinomial Naive Bayes Accuracy:", multinomial_accuracy)

Multinomial Naive Bayes Accuracy: 0.8888888888888888


In [17]:
print("Confusion Matrix:\n")
print(confusion_matrix(y_test, multinomial_predictions))

print("\nClassification Report:\n")
print(classification_report(y_test, multinomial_predictions))

Confusion Matrix:

[[14  0  0]
 [ 0 13  1]
 [ 2  1  5]]

Classification Report:

              precision    recall  f1-score   support

           0       0.88      1.00      0.93        14
           1       0.93      0.93      0.93        14
           2       0.83      0.62      0.71         8

    accuracy                           0.89        36
   macro avg       0.88      0.85      0.86        36
weighted avg       0.89      0.89      0.88        36



In [18]:
sample_data = X_test.iloc[:5]
print("Actual Classes:")
print(y_test.iloc[:5].values)

gaussian_pred = gaussian_model.predict(sample_data)
print("\nGaussian Predictions:")
print(gaussian_pred)

multinomial_pred = multinomial_model.predict(sample_data)
print("\nMultinomial Predictions:")
print(multinomial_pred)

Actual Classes:
[0 0 2 0 1]

Gaussian Predictions:
[0 0 2 0 1]

Multinomial Predictions:
[0 0 2 0 1]
